import random, string, time, asyncio, os, json, keyboard
from utils import *

def game():
    asyncio.run(start())
    time.sleep(1)
    asyncio.run(start1())
    time.sleep(1)
    asyncio.run(start2())
    time.sleep(1)
    asyncio.run(start3())
    time.sleep(1)
    asyncio.run(start4())
    time.sleep(1)
    asyncio.run(start5())
    time.sleep(1)
    asyncio.run(start6())
    time.sleep(1)
    asyncio.run(home())
    time.sleep(1)
    asyncio.run(home1())
    time.sleep(3.5)
    qONE()
    time.sleep(1.5)
    qTWO()
    time.sleep(1.5)
    qTHREE()
    time.sleep(1.5)
    qFOUR()
    time.sleep(3)
    end()
    time.sleep(10000)

game()